# Generated by Django 2.2.6 on 2019-11-24 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='motto',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('0', 'like'), ('1', 'comment')], max_length=20)),
                ('at_person', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=280, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moments.Status')),
            ],
        ),
    ]
